### ISSUE TITLE
Performance has become very bad on Raspberry Pi 4

### ISSUE THREAD

**Issue by vanfanel** [AloXado320/sm64ex-alo#11]
HI there,

Latest commits (this one in particular--> https://github.com/AloXado320/sm64ex-alo/commit/1200ea7d4bb5fcab59f1ba574392857b2b7e21f5) have destroyed performance on the Raspberry Pi completely. The game now crawls at ~1-2 FPS.
Can you please rollback this one or fix it?

**Comment by AuroraWright** [comment]
On a related note, performance degradation (stutters when changing areas) can also be seen on Nintendo Switch when using higher quality textures as of that same commit. After some testing, I nailed it down to the framebuffer-related texture checksumming code in gfx_pc.c (I suppose it makes sense when it has to do that on larger textures). Maybe that code could be stubbed too when HAS_FRAMEBUFFER is 0?

**Comment by AloXado320** [comment]
Framebuffer should now be disabled if `TARGET_RPI` and/or `EXTERNAL_DATA` are enabled

**Comment by vanfanel** [comment]
@AloXado320 The engine doesn't build now:

```
src/pc/gfx/gfx_opengl.c: In function 'gfx_opengl_get_framebuffer':
src/pc/gfx/gfx_opengl.c:915:9: error: 'USE_FRAMEBUFFER' undeclared (first use in this function); did you mean 'GL_FRAMEBUFFER'?
     if (USE_FRAMEBUFFER) {
         ^~~~~~~~~~~~~~~
         GL_FRAMEBUFFER
src/pc/gfx/gfx_opengl.c:915:9: note: each undeclared identifier is reported only once for each function it appears in
src/pc/gfx/gfx_opengl.c: In function 'gfx_opengl_init':
src/pc/gfx/gfx_opengl.c:963:9: error: 'USE_FRAMEBUFFER' undeclared (first use in this function); did you mean 'GL_FRAMEBUFFER'?
     if (USE_FRAMEBUFFER) {
         ^~~~~~~~~~~~~~~
         GL_FRAMEBUFFER
src/pc/gfx/gfx_opengl.c: In function 'gfx_opengl_start_frame':
src/pc/gfx/gfx_opengl.c:1014:9: error: 'USE_FRAMEBUFFER' undeclared (first use in this function); did you mean 'GL_FRAMEBUFFER'?
     if (USE_FRAMEBUFFER) {
         ^~~~~~~~~~~~~~~
         GL_FRAMEBUFFER
src/pc/gfx/gfx_opengl.c: In function 'gfx_opengl_end_frame':
src/pc/gfx/gfx_opengl.c:1031:9: error: 'USE_FRAMEBUFFER' undeclared (first use in this function); did you mean 'GL_FRAMEBUFFER'?
     if (USE_FRAMEBUFFER) {
         ^~~~~~~~~~~~~~~
         GL_FRAMEBUFFER
make: *** [Makefile:1556: build/us_pc/src/pc/gfx/gfx_opengl.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by AloXado320** [comment]
Fixed, should build now

**Comment by vanfanel** [comment]
@AloXado320 Thank, it builds now but performance is still abysmal on the Pi... like 1-2 fps as I said.

**Comment by AloXado320** [comment]
Thanks @vanfanel for the Pi4 donation!

The issue was fixed and it was called by this function `set_vertex_buffer` which calls `glBufferSubData`
I guess GLES doesn't like this change and it lags, i fixed it by changing the function to `glBufferData` alongisde removing the init call added in the Framebuffer PR

**Comment by vanfanel** [comment]
@AloXado320 Thanks to you for the continuing work on this fantastic fork!
