### ISSUE TITLE
BitDW entrance painting doesn't change from Peach to Bowser

### ISSUE THREAD

**Issue by JovanLozanac** [AloXado320/sm64ex-alo#15]
**Describe the bug**
Before entering Bowser in the Dark World, you have this hallway where a painting of Peach slowly morphs into Bowser. In this version, when you enter, it is just Bowser, no Peach

**To Reproduce**
1. Go to the 8 Star Door
2. Enter it
3. You should see it now

**Expected behavior**
A painting of Peach, morphing into a painting of Bowser.

**Screenshots**
Currently on mobile so unfortunately no pictures, you could imavine the problem

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 x64
 - Version: the latest repo as of July 28 2021 built in sm64pcbuilder2, just like my previous issue

**Additional context**
I just want to complement you on your work, I mean, taking a game and making it more modern, good job

**Comment by AloXado320** [comment]
What are you flags and render api? OpenGL seems to be fine
![image](https://user-images.githubusercontent.com/38191089/127418412-2fdd0c41-418a-4230-8162-4e991e0ec930.png)

**Comment by JovanLozanac** [comment]
Rendering API is DirectX11.
I may sound like an incompetent idiot to you, but what are flags and how do I view the required info about flags?
![image](https://user-images.githubusercontent.com/81957444/127466513-8fb5bf17-29de-41d3-89cd-46e0bcca46d8.png)

This is OpenGL 2.1, it too is not working
![image](https://user-images.githubusercontent.com/81957444/127469082-daac0c52-bcc9-4199-b4ae-67ebc8735cce.png)

**Comment by AloXado320** [comment]
I'm not able to replicate this issue, so either it got fixed overtime or something different in your environment, closing.
