### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by Jacob1Tm** [AloXado320/sm64ex-alo#23]
**Describe the bug**
Building android version fails

**Screenshots**
![Screenshot_20220527-111109_Termux](https://user-images.githubusercontent.com/84023677/170669582-c9a7fead-5ece-4554-a917-7324ec73a786.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S20
 - OS: Android 12

**Comment by WryOpussum** [comment]
Install binutils dependency

**Comment by Jacob1Tm** [comment]
another error
![Screenshot_20220603-092939_Termux](https://user-images.githubusercontent.com/84023677/171808546-1da77fec-4153-4c02-8ed0-f17196d66550.jpg)

**Comment by WryOpussum** [comment]
Hmm. Wait for AloXado as he said he needs to fix android builds

**Comment by WryOpussum** [comment]
K it should work now. Just pull the latest changes via git pull

**Comment by Jacob1Tm** [comment]
umm after pull
![Screenshot_20220604-190310_Termux](https://user-images.githubusercontent.com/84023677/172017679-74db7e1b-47f1-403f-8c8c-9624da894853.jpg)

**Comment by WryOpussum** [comment]
mkdir ~/../usr/include/KHR
wget https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h -O ~/../usr/include/KHR/khrplatform.h

**Comment by Jacob1Tm** [comment]
thanks now it builded and works :)

**Comment by AloXado320** [comment]
Updated Android build steps, thanks guys.
