### ISSUE TITLE
Switch 60 fps? 

### ISSUE THREAD

**Issue by Gaelcraft** [AloXado320/sm64ex-alo#27]
How do I use 60 fps on the switch and also how do I apply the star road patch?

**Comment by AloXado320** [comment]
`make -j4 TARGET_SWITCH=1 HIGH_FPS_PC=1` for Switch 60fps
Star road patch won't work on this state yet, i plan to merge more stuff to this repo so i can make the patch smaller

**Comment by Gaelcraft** [comment]
Thanks

**Comment by Gaelcraft** [comment]
I'm sure I can apply odyssey moveset and dynos but I don't know where to find them and how to apply them but with star road I'm satisfied

**Comment by Gaelcraft** [comment]
or sm74
