### ISSUE TITLE
Switch with 60fps patch seems to play back at 30 fps

### ISSUE THREAD

**Issue by philipp-eisen** [AloXado320/sm64ex-alo#3]
Hey!
first off thanks for your work! It's great!

I have built for nintendo switch with the 60fps path. 
However, the sound and the image seem to be a 0.5 speed. Am I missing sth. obivious?

**Comment by AloXado320** [comment]
I'm very late but it was because at the time 60fps, didn't do switch changes, now if you apply it again it now runs properly at 60fps

**Comment by philipp-eisen** [comment]
Thanks for fixing 🎉
