### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by OsoaGH** [AloXado320/sm64ex-alo#32]
**Describe the bug**
When I try to build it gives an error. [Here](https://pastebin.com/FLMFx2Lc) is what I see in the console.

**To Reproduce**
1. Clone the repo
2. CD into the directory
3. `make VERSION=eu TARGET_BITS=64 WINDOWS_BUILD=1 WINDOWS_CONSOLE=1 RENDER_API=GL AUDIO_API=SDL2 CONTROLLER_API=SDL2`

**Expected behavior**
I expect it to build successfully

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Additional context**
Also doesn't work on sm64pcBuilder2.

**Comment by AloXado320** [comment]
EU was already fixed but i forgot to close this lol
