### ISSUE TITLE
I cant compile on termux

### ISSUE THREAD

**Issue by JustOlaia** [AloXado320/sm64ex-alo#33]
help i was trying to compile this on termux but i got this error, is there a way to fix it? 
![Screenshot_20221211_092738_com termux](https://user-images.githubusercontent.com/104322336/206915039-fb80a7ff-e7ad-4ff9-967a-acb7c854f194.jpg)

**Comment by AloXado320** [comment]
Closing this since i think it uses an outdated version, remember to use latest repo update and `make clean` while at it.
