### ISSUE TITLE
Banner and icon for 3DS are incorrect

### ISSUE THREAD

**Issue by Delta18-Git** [AloXado320/sm64ex-alo#35]
**Describe the bug**
The icon and banner resemble the placeholders from mkst's repo.

**Screenshots**
![banner](https://user-images.githubusercontent.com/64347927/208427889-ace67f60-0e17-45da-963c-318a8a327564.png)

![icon](https://user-images.githubusercontent.com/64347927/208427939-2e8e4553-35ac-4159-a34c-23fac26ffa07.png)

**Additional context**
Compiled on WSL.

**Comment by Delta18-Git** [comment]
I was able to get it to work by making the SMDH and BNR files usimg bannertool and smdhtool. However, on doing this I wasn't able to create a 3DSX and had to directly create a CIA as 3dsxtool wasn't able to open the SMDH file I had created, although makerom worked fine.

**Comment by AloXado320** [comment]
Updated files, 3DSX and CIA should have the same banner and icons now.
