### ISSUE TITLE
Camera doesn't move and Mario is invisible in Tower of the Wing Cap

### ISSUE THREAD

**Issue by nolemretaWxd** [AloXado320/sm64ex-alo#36]
How to reproduce:

1. Enter Tower of the Wing Cap

Mario is invisible in that level, and camera doesn't move. After returning to Peach's Castle, camera will work again, and Mario will be visible

![obraz](https://user-images.githubusercontent.com/31414969/209874541-69e9490f-0aa5-46e9-8b21-a7adfee276dd.png)

Compile options: `make TEXTURE_FIX=1 DISCORDRPC=1 TEXTSAVES=1 EXTERNAL_DATA=1 EXT_OPTIONS_MENU=1 BETTERCAMERA=1 QOL_FIXES=1 QOL_FEATURES=1 MOUSE_ACTIONS=1 NODRAWINGDISTANCE=1`
Game was builded 28 December 2022 at 21:04 (UTC) from master branch
ROM region: US

**Comment by AloXado320** [comment]
Fixed
