### ISSUE TITLE
Cant compile on Linux

### ISSUE THREAD

**Issue by larkjkj** [AloXado320/sm64ex-alo#38]
i just cloned the repo, but the rom, and typed "make" and it cant extract the assets

Error message:
lark@archlinux ~/P/A/sm64ex-alo (master) [2]> make -j4
Traceback (most recent call last):
  File "/home/lark/Projects/Alexado/sm64ex-alo/extract_assets.py", line 298, in <module>
    main() if __name__ == "__main__" else None
    ^^^^^^
  File "/home/lark/Projects/Alexado/sm64ex-alo/extract_assets.py", line 169, in main
    ["make", "-s", "-C", "tools/sm64tools/", "n64graphics" + winext, "mio0" + winext]
                                             ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'winext' where it is not associated with a value
Makefile:404: *** Failed to extract assets from US ROM.  Pare.

1. Clone repo
2. Pick up a rom rename to baserom.us and put on the repo folder
3. Type Make
4. error

I'm on Arch and installed all dependencies and everything_

**Comment by AloXado320** [comment]
Solved
