### ISSUE TITLE
EXTERNAL_DATA=1 Builds will not run

### ISSUE THREAD

**Issue by DraeTheHedgehog** [AloXado320/sm64ex-alo#41]
I've compiled a sm64ex-alo build with the EXTERNAL_DATA flag set to 1 but every time I try to start the build it crashes

1. clone the repo
2. add the legally acquired rom into the repo folder
3. open terminal
4. compile like so "make EXTERNAL_DATA=1"
5. Run

It should run perfectly fine but it does not do so.

![image](https://github.com/AloXado320/sm64ex-alo/assets/52857186/4a02c61a-9a04-43cf-a164-e4b1a40e4ac8)

I'm using Linux Mint

**Comment by AloXado320** [comment]
Fixed on commit 7a97f0c
