### ISSUE TITLE
bettercam.c - Compile error

### ISSUE THREAD

**Issue by bkacjios** [AloXado320/sm64ex-alo#45]
![image](https://github.com/AloXado320/sm64ex-alo/assets/3247233/0b5f8d5b-ab6a-4e3c-aa89-7362f6255ab9)

Looks like a regression caused by the newly added ifdef's around `gPuppyOptions.debugCam` only if `EXT_DEBUG_MENU` is set.

**Comment by AloXado320** [comment]
Fixed on commit a65801f
