### ISSUE TITLE
[Feature request] Hide mouse cursor in FULLSCREEN mode

### ISSUE THREAD

**Issue by vanfanel** [AloXado320/sm64ex-alo#5]
**Describe the bug**
Mouse cursor is shown in fullscreen mode.

**To Reproduce**
1. Start the game
2. Activate the fullscreen option on the video settings
3. See the mouse cursor on screen

**Expected behavior**
Mouse cursor shouldn't show up in fullscreen mode (as in sm64ex).

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux
 - Version 10

**Additional context**
A simple call to SDL_ShowCursor(FALSE) is enough to hide the mouse cursor, so it's a very easy thing to implement I guess.

**Comment by vanfanel** [comment]
@AloXado320 It seems you force the cursor to be on screen in this block: https://github.com/AloXado320/sm64ex-alo/blob/acf9b80470152e149f6cfe5a8d63ef4efb8a2650/src/pc/controller/controller_sdl2.c#L149

And `MOUSE_ACTIONS` is defined in https://github.com/AloXado320/sm64ex-alo/blob/acf9b80470152e149f6cfe5a8d63ef4efb8a2650/Makefile#L649

So, having the extra options menu forces the mouse cursor to be on screen... That doesn't make much sense in my humble opinion.

**Comment by AloXado320** [comment]
Done as of 1d8e539
