### ISSUE TITLE
Game is very slow since latest commit

### ISSUE THREAD

**Issue by vanfanel** [AloXado320/sm64ex-alo#6]
**Describe the bug**
The game runs VERY slowly since commit https://github.com/AloXado320/sm64ex-alo/commit/1d8e539b3e4e262b333cd53652a35a08fa071989

Cursor seems to be shown in a frame and hidden on the next frame, too.

**To Reproduce**
1. Start the game
2. See it running slowly

**Expected behavior**
Game running at normal speed.

**Desktop (please complete the following information):**
 - OS: Debian GNU Linux 10, SDL2 on KMSRD and latest stable MESA

**Additional context**
Clearly this commit is causing the slowdown:
https://github.com/AloXado320/sm64ex-alo/commit/1d8e539b3e4e262b333cd53652a35a08fa071989

**Comment by AloXado320** [comment]
c6236a0 should fix it

**Comment by vanfanel** [comment]
Issue is now fixed via https://github.com/AloXado320/sm64ex-alo/commit/c6236a0cdcdacea4e79b66ad9df7be59f3c4c258

Closing this, thanks a lot!
