### ISSUE TITLE
Can't build PC version with HIGH_FPS_PC

### ISSUE THREAD

**Issue by vanfanel** [AloXado320/sm64ex-alo#8]
**Describe the bug**
It's impossible to build the PC version with `-HIGH_FPS_PC=1` with current GIT code, because of this:
`
pc_main.c:(.text+0x179): undefined reference to send_display_list
`

**To Reproduce**
Try to build the PC version with -HIGH_FPS_PC=1:
`make  HIGH_FPS_PC=1 -j4
`

**Desktop (please complete the following information):**
Lubuntu 20.04 x86_64, Debian 10 aarch64

**Additional context**

**Comment by AloXado320** [comment]
Fixed #7

**Comment by vanfanel** [comment]
@AloXado320 Thanks!
