### ISSUE TITLE
Inconsistent vblank period detection

### ISSUE THREAD

**Issue by vanfanel** [AloXado320/sm64ex-alo#9]
**Describe the bug**
There's a message appearing only some times when the game is launch:
`could not determine swap interval, falling back to timer sync`

Seems to be because this call to `test_vsync()` shows different results each time:
https://github.com/AloXado320/sm64ex-alo/blob/3924724f3f1ab397088c7a98bb0bf1d59fc7cce3/src/pc/gfx/gfx_sdl2.c#L165

Engine was built with `make  HIGH_FPS_PC=1 -j4`

**To Reproduce**
Run the game and watch the log.

**Expected behavior**
This message shouldn't appear on a sane SDL2/GL environment with a 60Hz video mode.

**Desktop (please complete the following information):**
Lubuntu 20.04 x86_64, Debian 10 aarch64, ~60Hz phisical video mode.

**Comment by AloXado320** [comment]
sm64ex had that issue, but it has been addresed in sm64pc/sm64ex#488
Should be fine now that i merge over those changes in 49f73f1
